### ISSUE TITLE
Is there a conflict with PHP7?

### ISSUE THREAD

**Issue by hurkal** [alaca/xmldb#2]
https://github.com/alaca/xmldb/blob/5616280d70a561c13bd25fce46b6fdef3d1a420b/xmldb.php#L112

This line causes endless process, nothing seems on screen.

**Comment by alaca** [comment]
Hi, check is there any .lock file left in data directory. Delete it and try again. 
Let me know if that works

**Comment by hurkal** [comment]
Solved. Problem occured because of the location of "data" directory. Realized that the directory should be placed in the same location with xmldb.php.

Thanks for reply and xmldb class.
